export const BookData = [
    {
        id: 0,
        book_name: "Harry Potter and the Philosopher's Stone",
        book_description: "Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry's eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin!",
        book_url: "https://m.media-amazon.com/images/I/5165He67NEL._SY346_.jpg",
        pdf_url: "https://files.addictbooks.com/wp-content/uploads/2022/11/Harry-Potter-and-The-Philosophers-Stone.pdf",
        print_length: "345 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "305",
    },
    {
        id: 1,
        book_name: "The Jungle Book",
        book_description: "Join Mowgli the Man-cub as he embarks on a dangerous journey through the jungle to escape the man-eating tiger Shere Khan. In his attempt to reach the Man-village, Mowgli discovers a whole new way of life when he meets the lovable bear, Baloo. The pair strike up a close friendship but will Mowgli reach the safety of the village before it is too late? Find out in this beautiful Disney storybook with an eye-catching lenticular cover.",
        book_url: "https://m.media-amazon.com/images/I/51cCdjGzuVL._SX364_BO1,204,203,200_.jpg",
        pdf_url: "https://dn720006.ca.archive.org/0/items/the-jungle-book-rudyard-kipling/The%20Jungle%20Book_Rudyard%20Kipling.pdf",
        print_length: "200 pages",
        language: "English",
        author_name: "Rudyard Kipling",
        price: "340",
    },
    {
        id: 2,
        book_name: "Treasure Island",
        book_description: "Think of the high seas and of a buccaneer ship; of a wild seaman with a sea chest full of gold; of Long John Silver; of a buried treasure and of young Jim Hawkins, the boy with the treasure map the key to it all. This is the Treasure Island and if you don't think of all this, the pirates will hunt you down and when they find you, for find you they sure will, they will truss you and carry you back to their ship and just before they feed you to the sharks, as you walk the gangplank with a sword digging sharp and sure into your back, they will sing their one last song for you. “Fifteen men on the dead man's chest Yo-ho-ho and a bottle of rum!",
        book_url: "https://m.media-amazon.com/images/I/512c4l+AUrS._SX258_BO1,204,203,200_.jpg",
        pdf_url: "https://freeclassicebooks.com/Robert%20Louis%20Stevenson/Treasure%20Island.pdf",
        print_length: "236 pages",
        language: "English",
        author_name: "R.L. Stevenson",
        price: "108",
    },
    {
        id: 3,
        book_name: "From the Earth to the Moon",
        book_description: "Written almost a century before the daring flights of the astronauts, Jules Verne’s prophetic novel of man’s race to the stars is a classic adventure tale enlivened by broad satire and scientific acumen. When the members of the elite Baltimore Gun Club find themselves lacking any urgent assignments at the close of the Civil War, their president, Impey Barbicane, proposes that they build a gun big enough to launch a rocket to the moon. But when Barbicane’s adversary places a huge wager that the project will fail and a daring volunteer elevates the mission to a “manned” flight, one man’s dream turns into an international space race. A story of rip-roaring action, humor, and wild imagination, From the Earth to the Moon is as uncanny in its accuracy and as filled with authentic detail and startling immediacy as Verne’s timeless masterpieces 20,000 Leagues Under the Sea and Around the World in Eighty Days.",
        book_url: "https://m.media-amazon.com/images/I/61r44FrbhLL._SX302_BO1,204,203,200_.jpg",
        pdf_url: "https://dn720001.ca.archive.org/0/items/in.ernet.dli.2015.531850/2015.531850.From-The_text.pdf",
        print_length: "240 pages",
        language: "English",
        author_name: "Jules Verne",
        price: "202",
    },
    {
        id: 4,
        book_name: "Around The World In Eighty Days",
        book_description: "October 2, 1872, Reform Club, London. There is an article in the Daily Telegraph estimating that one can go round the world in eighty days. Phileas Fogg, a rich English gentleman, engages in a conversation with his partners at whist about the possibility of it. and this is what it leads to: “I will bet twenty thousand pounds against anyone who wishes, that I will make the tour of the world in eighty days or less; in nineteen hundred and twenty hours or a hundred and fifteen thousand two hundred minutes. Do you accept?”And soon, Fogg is on the 8.45 p.m. train to Italy from London with his French servant, Passe-partout. From trains to steamers to elephants, as Fogg travels across the four continents and different time zones, braving the unexpected, will he be able to circumnavigate the globe in eighty days? Will Phileas Fogg win the bet?Written during the Franco-Prussian War, Jules Verne’s Around the World in Eighty Days is a thrilling and lively adventure novel. Reimagined across various art forms, this unforgettable classic continues to challenge the spirit of adventure in its readers.",
        book_url: "https://m.media-amazon.com/images/I/510EvAURpTL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        pdf_url: "https://www.ibiblio.org/ebooks/Verne/Eighty_Days.pdf",
        print_length: "248 pages",
        language: "English",
        author_name: "Jules Verne",
        price: "140",
    },
    {
        id: 5,
        book_name: "Toy Story",
        book_description: "Everyone's favorite toys are hitting the big screen. But the fun can be taken home and enjoyed over and over again with this brand-new storybook collection, timed to release with Disney-Pixar's Toy Story 3! Sure to draw in a new generation of fans of these extremely popular movies, the collection features retellings of all three movies, plus brand-new stories about Woody, Buzz, Jessie, Rex and the rest of the gang. Young readers are in for hours of rollicking good fun. With gilded pages and over 250 illustrations, this latest addition to the best-selling storybook collection series will make the perfect gift.",
        book_url: "https://i5.walmartimages.com/seo/Toy-Story-Storybook-Collection-Hardcover-by-Disney-Books-9781423115748_ea0557b7-c118-4426-9817-46ae4345e970.f83379f001aa2b76f741bfada7ead022.jpeg?odnHeight=640&odnWidth=640&odnBg=FFFFFF",
        pdf_url: "https://archive.org/details/isbn_9781423159841",
        print_length: "172 pages",
        language: "English",
        author_name: "Pete Docter, Andrew Stanton, Alec Sokolow, Joss Whedon, Joe Ranft",
        price: "286",
    },
    {
        id: 6,
        book_name: "All Time Favourites for Children",
        book_description: "Shoot all the bluejays you want, if you can hit 'em, but remember it's a sin to kill a mockingbird.' A lawyer's advice to his children as he defends the real mockingbird of Harper Lee's classic novel - a black man falsely charged with the rape of a white girl. Through the young eyes of Scout and Jem Finch, Harper Lee explores with exuberant humour the irrationality of adult attitudes to race and class in the Deep South of the 1930s. The conscience of a town steeped in prejudice, violence and hypocrisy is pricked by the stamina of one man's struggle for justice. But the weight of history will only tolerate so much. To Kill a Mockingbird is a coming-of-age story, an anti-racist novel, a historical drama of the Great Depression and a sublime example of the Southern writing tradition.",
        book_url: "https://m.media-amazon.com/images/I/71Wcm0WWBnS._SL1500_.jpg",
        pdf_url: "https://books.google.co.in/books?id=VCQrEAAAQBAJ&printsec=frontcover#v=onepage&q&f=false",
        print_length: "320 pages",
        language: "English",
        author_name: "Ruskin Bond",
        price: "138",
    },
    {
        id: 7,
        book_name: "Akbar-Birbal",
        book_description: "The stories of ?Akbar and Birbal? are the most cherished folklores of India that have been passed from one generation to another, enthralling both young and adult readers. This book is a beautifully illustrated compilation of several tales of wit and wisdom, built upon the themes of loyalty and friendship.",
        book_url: "https://m.media-amazon.com/images/I/71IEUDALDML._SL1000_.jpg",
        pdf_url: "https://books.google.co.in/books?id=LN9ptrHH7EoC&printsec=frontcover#v=onepage&q&f=false",
        print_length: "320 pages",
        language: "English",
        author_name: "Ankur Warikoo",
        price: "312",
    },
    {
        id: 8,
        book_name: "Harry Potter and the Chamber of Secrets",
        book_description: "Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start. Students are found as through turned to stone . Dobby's sinister predictions seem to be coming true.These new editions of the classic and internationally bestselling, multi-award-winning series feature instantly pick-up-able new jackets by Jonny Duddle, with huge child appeal, to bring Harry Potter to the next generation of readers. It's time to PASS THE MAGIC ON .",
        book_url: "https://m.media-amazon.com/images/I/51yzj3H34aL._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        pdf_url: "https://drive.google.com/file/d/17Wsbk7f48y1qzOD1fyH-HaJm3RDsYNAM/preview",
        print_length: "224 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "310",
    },
    {
        id: 9,
        book_name: "The BiG Book of Kids Puzzles",
        book_description: "This vibrant and charming puzzle book is packed with entertaining new takes on classic puzzles, lovable cartoon illustrations, and an irrepressible sense of fun.",
        book_url: "https://i5.walmartimages.com/seo/The-Big-Book-of-Kids-Puzzles-Paperback-9781784282325_21e47a9b-9ccc-4f07-be58-26d1fdb1fb56.1609ee1f2857297d6c643f2177e76133.jpeg?odnHeight=640&odnWidth=640&odnBg=FFFFFF",
        pdf_url: "https://docs.google.com/file/d/0ByEJ-e86Aje4UzJRMEdUbGd5dTg/view?resourcekey=0-0LB_XXnH_zUdOxC4HM3THA",
        print_length: "384 pages",
        language: "English",
        author_name: "Mark Manson",
        price: "272",
    },
    {
        id: 10,
        book_name: "The Kid Who Came From Space Paperback",
        book_description: "The stunning new 10+ story from the bestselling and award-winning author of time travelling with a hamster, for anyone who loved the humour of wall-e, the action of star Wars and the deeply touching emotion of et. A small village in the wilds of northumberland is rocked by the disappearance of twelve-year-old Tammy. Only her twin brother, Ethan, knows she is safe  and the extraordinary truth of where she is. It is a secret he must keep, or risk never seeing her again. But that doesn't mean hes going to give up. Together with his friend Iggy and the mysterious (and very hairy) hellyann, Ethan teams up with a spaceship called Philip, and Suzy the trained chicken, for a nail-biting chase to get his sister backthat will take him further than anyone has ever been before.",
        book_url: "https://m.media-amazon.com/images/I/81XFiVELMBL._SL1500_.jpg",
        pdf_url: "https://books.google.co.in/books?id=PoScDwAAQBAJ&printsec=frontcover#v=onepage&q&f=false",
        print_length: "208 pages",
        language: "English",
        author_name: "Ross Welford",
        price: "249",
    },
    {
        id: 11,
        book_name: "Tenali-Raman",
        book_description: "The classic stories of the Vikatakavi, Tenali Raman, with valuable morals are passed on from generation to generation. This beautifully illustrated book is a compilation of witty Tenali Raman stories that ignites the young minds and captures their imagination. Each tale in this book reveals Tenali’s wisdom, wit and fair play.",
        book_url: "https://m.media-amazon.com/images/I/71tVvU10bzL._SL1000_.jpg",
        pdf_url: "/path/to/book/pdf1.pdf",
        print_length: "256 pages",
        language: "English",
        author_name: "Seth Godin",
        price: "294",
    },
    {
        id: 12,
        book_name: "Harry Potter and the Prisoner of Azkaban",
        book_description: "When the Knight Bus crashes through the darkness and screeches to a halt in front of him, it's the start of another far from ordinary year at Hogwarts for Harry Potter. Sirius Black, escaped mass-murderer and follower of Lord Voldemort, is on the run - and they say he is coming after Harry. In his first ever Divination class, Professor Trelawney sees an omen of death in Harry's tea leaves . But perhaps most terrifying of all are the Dementors patrolling the school grounds, with their soul-sucking kiss.",
        book_url: "https://m.media-amazon.com/images/I/51StPSSsneL._SX332_BO1,204,203,200_.jpg",
        pdf_url: "/path/to/book/pdf1.pdf",
        print_length: "480 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "305",
    },
    {
        id: 13,
        book_name: "The Girl Who Drank The Moon",
        book_description: "The Triwizard Tournament is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter - but that doesn't stop Harry dreaming that he will win the competition. Then at Hallowe'en, when the Goblet of Fire makes its selection, Harry is amazed to find his name is one of those that the magical cup picks out. He will face death-defying tasks, dragons and Dark wizards, but with the help of his best friends, Ron and Hermione, he might just make it through - alive!These new editions of the classic and internationally bestselling, multi-award-winning series feature instantly pick-up-able new jackets by Jonny Duddle, with huge child appeal, to bring Harry Potter to the next generation of readers. It's time to PASS THE MAGIC ON.",
        book_url: "https://m.media-amazon.com/images/I/7138zaESFhL._SL1250_.jpg",
        print_length: "640 pages",
        language: "English",
        author_name: "Kelly Barnhill",
        price: "439",
    },
    {
        id: 14,
        book_name: "Story Theives",
        book_description: "Dark times have come to Hogwarts. After the Dementors' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord's return, but Harry is not alone: a secret order gathers at Grimmauld Place to fight against the Dark forces. Harry must allow Professor Snape to teach him how to protect himself from Voldemort's savage assaults on his mind. But they are growing stronger by the day and Harry is running out of time.",
        book_url: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781481409193/story-thieves-9781481409193_hr.jpg",
        print_length: "816 pages",
        language: "English",
        author_name: "James reiley",
        price: "475",
    },
    {
        id: 15,
        book_name: "Harry Potter and the Half Blood Prince",
        book_description: "When Dumbledore arrives at Privet Drive one summer night to collect Harry Potter, his wand hand is blackened and shrivelled, but he does not reveal why. Secrets and suspicion are spreading through the wizarding world, and Hogwarts itself is not safe. Harry is convinced that Malfoy bears the Dark Mark: there is a Death Eater amongst them. Harry will need powerful magic and true friends as he explores Voldemort's darkest secrets, and Dumbledore prepares him to face his destiny.",
        book_url: "https://m.media-amazon.com/images/I/51XgBz54o3L._SY264_BO1,204,203,200_QL40_FMwebp_.jpg",
        print_length: "560 pages",
        language: "English",
        author_name: "J.K. Rowling",
        price: "429",
    },
    {
        id: 16,
        book_name: "Believe in Yourself",
        book_description: "As he climbs into the sidecar of Hagrid's motorbike and takes to the skies, leaving Privet Drive for the last time, Harry Potter knows that Lord Voldemort and the Death Eaters are not far behind. The protective charm that has kept Harry safe until now is now broken, but he cannot keep hiding. The Dark Lord is breathing fear into everything Harry loves, and to stop him Harry will have to find and destroy the remaining Horcruxes. The final battle must begin - Harry must stand and face his enemy.",
        book_url: "https://m.media-amazon.com/images/I/61RlLYVbDSL._SL1500_.jpg",
        print_length: "640 pages",
        language: "English",
        author_name: "Joseph Murphy",
        price: "431",
    }
   
]